title: repository
email: lvrodriguesline@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Repositório de componentes Java gerenciado pelo Maven.
baseurl: "/repository" # the subpath of your site, e.g. /blog
url: "https://lvrodrigues.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username: LVRodrigues

# Descomente abaixo para habilitar a paginação.
paginate: 3
paginate_path: "/page:num/"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-category-pages

lsi: false
safe: true
#source: https://github.com/LVRodrigues/repository.git
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

defaults:
  scope:
    path: ""
    type: posts
  values:
    layout: post